#!/bin/bash
clear

# © RDY SOFTWARE | 2016 - 2017 All rights reserved

if [ $(id -u) -eq 0 ]
then
#----------------------------------------------------------------------------------#

if [ -e "/root/usuarios.db" ]
then
read -p "" name
 if [ $(cat /etc/passwd |grep "^$name:" |wc -l) -eq 0 ]; then
 echo "Usuario $name nao existe!"
 exit
 fi
 pids=$(ps -u $name |awk {'print $1'})
 kill "$pids" >/dev/null 2>/dev/null
 userdel $name 1>/dev/null 2>/dev/null
 echo "$name"
 exit
fi
#----------------------------------------------------------------------------------#
else

if [ -e "/usr/lib/klibc/bin/chooa" ]
then

read -p "" user
if cat /etc/passwd |grep $user: > /dev/null
then

userdel --force $user > /dev/null 2>/dev/null
kill -9 `ps aux |grep -vi '[a-z]$user' |grep -vi '$user[a-z]' |grep -v '[1-9]$user' |grep -v '$user[1-9]' |grep $user |awk {'print $2'}` 2> /dev/null
echo "$user";
exit

else
clear
echo -e "Usuario $user nao existe!"
exit
fi
#----------------------------------------------------------------------------------#

else

if [ -e "/etc/VpsPackdir/limite" ]
then

read -p "" user
if cat /etc/passwd |grep $user: > /dev/null
then

userdel --force $user > /dev/null 2>/dev/null
kill -9 `ps aux |grep -vi '[a-z]$user' |grep -vi '$user[a-z]' |grep -v '[1-9]$user' |grep -v '$user[1-9]' |grep $user |awk {'print $2'}` 2> /dev/null
echo "$user";
exit

else
clear
echo -e "Usuario $user nao existe!"
exit
fi
#----------------------------------------------------------------------------------#

else
if echo $(id) |grep sudo > /dev/null
then
echo -e "Seu usuario esta no grupo sudo!"

fi
fi
fi
fi
fi